# Generated by Django 5.1 on 2024-08-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0005_alter_graphmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='graphmodel',
            table='MANUFACTURING_TABLE',
        ),
    ]
