# Generated by Django 5.1 on 2024-08-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chw_in_temp', models.FloatField()),
                ('chw_out_temp', models.FloatField()),
                ('cow_in_temp', models.FloatField()),
                ('cow_out_temp', models.FloatField()),
            ],
            options={
                'db_table': 'MACHINES_TABLE',
                'managed': False,
            },
        ),
    ]
