# Generated by Django 5.1 on 2024-08-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detailed_Graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temperaturedata',
            table='DEVICES_TABLE',
        ),
    ]
