# Generated by Django 5.1 on 2024-08-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureLogin', '0002_alter_user_date_joined_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='SYS.SECURE_TABLE',
        ),
    ]
