# Generated by Django 5.1 on 2024-08-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureLogin', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='LOGIN_TABLE',
        ),
    ]
