# Generated by Django 5.1 on 2024-08-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureLogin', '0010_customuser_delete_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='login_users',
        ),
    ]
