# Generated by Django 5.1 on 2024-08-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureLogin', '0011_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='CUSTOMUSER',
        ),
    ]
