# Generated by Django 5.1 on 2024-08-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureLogin', '0015_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='LOGIN_USER_CUSTOM',
        ),
    ]
