# Generated by Django 5.1 on 2024-09-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureLogin', '0017_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='LOGIN_USER_CUSTOM',
        ),
    ]
