# Generated by Django 5.1 on 2024-09-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureLogin', '0018_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='LOGIN_USER_TABLE',
        ),
    ]
