# Generated by Django 5.1 on 2024-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chw_in_temp', models.FloatField()),
                ('chw_out_temp', models.FloatField()),
                ('cow_in_temp', models.FloatField()),
                ('cow_out_temp', models.FloatField()),
                ('device_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'DEVICES_TABLE',
            },
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
