# Generated by Django 5.1 on 2024-08-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_product_delete_machine'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='MACHINE_TABLE',
        ),
    ]
