# Generated by Django 5.1 on 2024-08-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_alter_product_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Machine',
        ),
    ]
