# Generated by Django 5.1 on 2024-08-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0004_rename_product_machine'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='machine',
            table='DEVICES_TABLE',
        ),
    ]
