# Generated by Django 5.1 on 2024-08-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0005_alter_machine_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='machine',
            table='PRODUCTS_TABLE',
        ),
    ]
