# Generated by Django 5.1 on 2024-08-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0006_alter_machine_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine',
            new_name='ProductModel',
        ),
    ]
