# Generated by Django 5.1 on 2024-08-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0007_rename_machine_productmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
    ]
