# Generated by Django 5.1 on 2024-08-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0009_device_delete_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='MANUFACTURING_TABLE',
        ),
    ]
