# Generated by Django 5.1 on 2024-08-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0010_alter_device_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='htg_hr_hi_sp',
            new_name='htg_pr_hi_sp',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='ovrflw_lgt_temp',
            new_name='ovrflw_ltg_temp',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='sray_temp',
            new_name='spray_temp',
        ),
    ]
